### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by DrewLukas** [liranbg/linkedin-learning-downloader#11]
Hi,

What's the reason why I get 'Access to <slug> is DENIED' in command prompt? A couple days ago everything was working fine.

Somebody an idea

D:\Process\LinkedIn>python linkedin_learning.py
2018-11-17 15:47:32,281 asyncio      DEBUG    Using selector: SelectSelector
2018-11-17 15:47:32,311 root         INFO     [*] -------------Login-------------
2018-11-17 15:47:32,312 root         INFO     [*] Login step 1 - Getting CSRF token...
2018-11-17 15:47:32,774 root         DEBUG    [*] CSRF: 497f9701-76f4-42d7-8314-78993b5e6e83
2018-11-17 15:47:32,774 root         INFO     [*] Login step 1 - Done
2018-11-17 15:47:32,775 root         INFO     [*] Login step 2 - Logging In...
2018-11-17 15:47:33,664 root         INFO     [*] Login step 2 - Done
2018-11-17 15:47:33,665 root         INFO     [*] -------------Done-------------
2018-11-17 15:47:33,665 root         INFO     [*] -------------Fetching Course-------------
2018-11-17 15:47:34,348 asyncio      ERROR    Unclosed connection
client_connection: Connection<ConnectionKey(host='www.linkedin.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=-1125722543)>
2018-11-17 15:47:34,351 root         INFO     [*] Access to Making Sense of the CSS Box Model is DENIED
2018-11-17 15:47:34,352 root         INFO     [*] -------------Done-------------

**Comment by lucaterpirla** [comment]
I have the same error and it is the first time that I use this tool.

**Comment by ghost** [comment]
I'm also having this.

**Comment by ionsilviumihai** [comment]
Did you manage to fix this?

**Comment by DrewLukas** [comment]
No, still having the same error message 'Access to is DENIED'. Does anyone have a solution?

**Comment by MagicRico** [comment]
I don't know if someone already solved this problem. Here is what I did

I opened linkedin_learning.py and went to line 114 (where it is checking if Granded or Denied)
I just commented the if and return
#if not course.unlocked:
            # Nothing to do here
#    return
Saved the script and started it again
It works for me

This is for sure not a pretty solution but a good bypass
Enjoy guys

**Comment by MagicRico** [comment]
> 
> 
> No, still having the same error message 'Access to is DENIED'. Does anyone have a solution?

I don't know if someone already solved this problem. Here is what I did

I opened linkedin_learning.py and went to line 114 (where it is checking if Granted or Denied)
I just commented the if and return
#if not course.unlocked:
#Nothing to do here
#return
Saved the script and started it again
It works for me

This is for sure not a pretty solution but a good bypass
Enjoy guys

**Comment by ghost** [comment]
MagicRico, you are a hero. Thank you!

**Comment by shasureshkumar** [comment]
I have changed 
#if not course.unlocked:
#Nothing to do here
#return
After this change I am getting KeyError: 'url'

**Comment by MagicRico** [comment]
> 
> 
> I have changed
> #if not course.unlocked:
> #Nothing to do here
> #return
> After this change I am getting KeyError: 'url'

Can you make a screenshot please

**Comment by DrewLukas** [comment]
MagicRico, thank you! It worked!

**Comment by MagicRico** [comment]
> 
> 
> MagicRico, thank you! It worked!

You are welcome

**Comment by shasureshkumar** [comment]
> > I have changed
> > #if not course.unlocked:
> > #Nothing to do here
> > #return
> > After this change I am getting KeyError: 'url'
> 
> Can you make a screenshot please

Please find the attachment, please.

<img width="863" alt="screenshot 2018-12-06 at 9 19 48 am" src="https://user-images.githubusercontent.com/11661366/49560374-1aeca000-f938-11e8-87c4-f40715144a84.png">


![screenshot 2018-12-06 at 9 18 02 am](https://user-images.githubusercontent.com/11661366/49560339-f42e6980-f937-11e8-99bb-05ffb20c90be.png)

**Comment by MagicRico** [comment]
> 
> 
> > > I have changed
> > > #if not course.unlocked:
> > > #Nothing to do here
> > > #return
> > > After this change I am getting KeyError: 'url'
> > 
> > 
> > Can you make a screenshot please
> 
> Please find the attachment, please.
> 
> <img alt="screenshot 2018-12-06 at 9 19 48 am" width="863" src="https://user-images.githubusercontent.com/11661366/49560374-1aeca000-f938-11e8-87c4-f40715144a84.png">
> 
> ![screenshot 2018-12-06 at 9 18 02 am](https://user-images.githubusercontent.com/11661366/49560339-f42e6980-f937-11e8-99bb-05ffb20c90be.png)

I tried to download the course 'git-essential-training'
first time I started the script I had same errors, it only achieved to create the chapters structure
then I connected to the course on linkedin website to check if I could watch it correctly and btw I checked the video url if it doesn't look strange. I didn't see anything
So I started again and again, after two time, it completed to download (you can see the screenshot).

If you already have the chapters structure then i can only advice you to keep trying to start the script
![it achieved to download](https://user-images.githubusercontent.com/45574223/49563014-eb01c480-f958-11e8-9d24-a66736f4310f.PNG)

PS : don't mind if my script called lld.py (this is exactly the same script just renamed to type it faster)

**Comment by shasureshkumar** [comment]
I tried many times from yesterday, but no luck.
I have linked organization account for LinkedIn learning into my personal account.
In username and password section I gave my personal account details, Am I doing correctly?
Advice me how to get rid of this.

After I tried so many times, I started getting KeyError: 'elements' (PFA)
![screenshot 2018-12-06 at 10 55 10 am](https://user-images.githubusercontent.com/11661366/49563355-9143cf00-f945-11e8-960f-c10964bad1ae.png)

**Comment by MagicRico** [comment]
> 
> 
> I tried many times from yesterday, but no luck.
> I have linked organization account for LinkedIn learning into my personal account.
> In username and password section I gave my personal account details, Am I doing correctly?
> Advice me how to get rid of this.

1st) try if you can connect to your linkedin account and watch the courses
2nd) After starting the script and failed, check if it already built the folders structure (name of the courses, chapters name)?
3rd) don't give up

**Comment by shasureshkumar** [comment]
Hi MagicRico,
Still I am getting the same issue, not able to download the videos... 
<img width="1424" alt="screenshot 2018-12-20 at 9 33 02 am" src="https://user-images.githubusercontent.com/11661366/50263165-80618600-043a-11e9-8ec3-ba3527cf44df.png">

**Comment by ghost** [comment]
Hi Sharuresh,

I've had this a few times but if you keep running the code without any changes it eventually works. Not sure what the issue is.

**Comment by sokart** [comment]
I have probably found the issue. Try to download no more than two courses at the time. 

The reason is that for each course and each video, the code generates a new request. That means if you have 10 courses with 50 videos each, you generate 500 requests at the same time. The system is unable to handle this amount of requests.

**Comment by shasureshkumar** [comment]
I gave only one course, for that only I was getting keyerror which I mentioned earlier.

**Comment by niels-numbers** [comment]
@shasureshkumar I had the same issue. The problem is that the purpose of this download version is to download the files asynchronous (this means it starts downloading all files at once rather then one by one). If you download even just a single course that contains a lot of videos the script may exit immediatly showing you the error

```
KeyError: 'url'
```

So I suggest you to use a script that downloads the videos one by one instead of asynchronously. The original repository https://github.com/mclmza/linkedin-learning-downloader has been taken down, but you can also use https://github.com/ha100/linkedin-learning-downloader for example.

**Comment by shasureshkumar** [comment]
@iwasherefirst2, I have tried your new code and getting the below error.

`ERROR - Can't download the video [........], probably is only for premium users`

FYI, I have linked my corporate account with my personal account (I can view the video).

**Comment by progerjkd** [comment]
> > No, still having the same error message 'Access to is DENIED'. Does anyone have a solution?
> 
> I don't know if someone already solved this problem. Here is what I did
> 
> I opened linkedin_learning.py and went to line 114 (where it is checking if Granted or Denied)
> I just commented the if and return
> #if not course.unlocked:
> #Nothing to do here
> #return
> Saved the script and started it again
> It works for me
> 
> This is for sure not a pretty solution but a good bypass
> Enjoy guys

That worked for me. Thank you!

**Comment by mukash** [comment]
#logging.info(f'[*] Access to {course.name} is {"GRANTED" if course.unlocked else "DENIED"}')
        #if not course.unlocked:
            # Nothing to do here
         #   return

i commented these lines and then it worked for me but you have to give the command python "linkedin_learning.py" everytime it completes until it say that your course is done.

**Comment by diieduarte** [comment]
*Download youtube-dl*

https://github.com/ytdl-org/youtube-dl


youtube-dl.exe --username "user" --password "pass" -o "C:\Users\user\Downloads\linkedin-learning-downloader-master\downloads\%(playlist_title)s\Lesson %(chapter_number)02d - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s" -f "bestvideo[height<=720]+bestaudio/best[height<=720]"  --playlist-start 1 --verbose --min-sleep-interval 90 --max-sleep-interval 130 https://www.linkedin.com/learning/python-para-data-scientist-avanzado/

**Comment by diieduarte** [comment]
--write-sub                      Write subtitle file

**Comment by shasureshkumar** [comment]
@diieduarte, When I use youtube-dl I am getting "ERROR: No video formats found;"  after one chapter downloaded.

`youtube-dl --username "user" --password "password" -o "/Users/sshanmugavel/Desktop/temp/linkedin-git/downloads/%(playlist_title)s/Lesson %(chapter_number)02d - %(chapter)s/%(playlist_index)s - %(title)s.%(ext)s" -f "bestvideo[height<=720]+bestaudio/best[height<=720]" --playlist-start 1 --verbose --write-sub --min-sleep-interval 90 --max-sleep-interval 130 https://www.linkedin.com/learning/git-essential-training` 



<img width="1421" alt="Screenshot 2019-04-22 at 10 17 51 AM" src="https://user-images.githubusercontent.com/11661366/56483505-fe689300-64e7-11e9-8261-b433dd30cfb3.png">

**Comment by liranbg** [comment]
fixed on #21 && #22
