### ISSUE TITLE
asyncio ERROR Unclosed connection

### ISSUE THREAD

**Issue by edwanyoike** [liranbg/linkedin-learning-downloader#12]
2018-11-27 13:10:51,121 asyncio      ERROR    Unclosed connection

client_connection: Connection<ConnectionKey(host='www.linkedin.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=-182393375643722223)>

2018-11-27 13:10:51,124 root         INFO     [*] Access to Learning Java Enterprise Edition is DENIED

**Comment by shasureshkumar** [comment]
Me too getting the same error

**Comment by MagicRico** [comment]
> 
> 
> 2018-11-27 13:10:51,121 asyncio ERROR Unclosed connection
> 
> client_connection: Connection<ConnectionKey(host='www.linkedin.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None, proxy_headers_hash=-182393375643722223)>
> 
> 2018-11-27 13:10:51,124 root INFO [*] Access to Learning Java Enterprise Edition is DENIED

Your problem is not about unclosed connection
Your problem is about the acess is DENIED
So I advise you to check in the tread DENIED, you will find the solution

**Comment by shasureshkumar** [comment]
Hi, I have linked organization account for LinkedIn learning into my personal account.
In username and password section I gave my personal account details, Am I doing correctly?
Advice me how to get rid of this.

**Comment by liranbg** [comment]
fixed on #21 && #22
