### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by zadesign** [liranbg/linkedin-learning-downloader#15]
Mac-Pro:linkedin-learning-downloader-master username$ python linkedin_learning.py
  File "linkedin_learning.py", line 35
    return f'{hours:02}:{minutes:02}:{seconds:02},{milliseconds:02}'
                                                                   ^
SyntaxError: invalid syntax

What can i do?
Thanks.

**Comment by dwicahyo-dev** [comment]
same here

**Comment by DamianMalik** [comment]
same for me

**Comment by abooddev** [comment]
same for me

**Comment by liranbg** [comment]
fixed on #21 && #22
