### ISSUE TITLE
How to skip the files that are already downloaded

### ISSUE THREAD

**Issue by pareshrz** [liranbg/linkedin-learning-downloader#5]
Please give me code to add in download file function so it checks if filename already exists, and if it does skips to the next file. From midway into downloading it gave me error that connection has been forcibly closed by remote host. When I ran it again it started from beginning downloading each video again

Thanks for the work you have done. I appreciate it a lot.

**Comment by MagicRico** [comment]
> 
> 
> Please give me code to add in download file function so it checks if filename already exists, and if it does skips to the next file. From midway into downloading it gave me error that connection has been forcibly closed by remote host. When I ran it again it started from beginning downloading each video again
> 
> Thanks for the work you have done. I appreciate it a lot.

If the file is already well downloaded then it skips it. The script checks already.

**Comment by liranbg** [comment]
fixed on #21 && #22
