### ISSUE TITLE
Received error 429 from server

### ISSUE THREAD

**Issue by AlfaIrawan** [liranbg/linkedin-learning-downloader#50]
Hello @liranbg ,

When I download 2 or 3 Time learning path always got an error

`for URI https://lor1-app33648.prod.linkedin.com:7220/learning-api/learningApiInit`

Is this normal?Because after that my LinkedIn Learning will down 1 day, in next day I will up again

Regards,
Alfa Irawan

**Comment by fbpdh** [comment]
This is essentially a too many requests error. It means you downloaded a lot and the server has rejected your connection. Have you tried some time later?

**Comment by AlfaIrawan** [comment]
@fbpdh Yes, after 12-24 hour it will be normal again. I'm just afraid LinkedIn blocking my account.
