### ISSUE TITLE
Error message: KeyError: 'transcript'

### ISSUE THREAD

**Issue by NawTan** [liranbg/linkedin-learning-downloader#6]
While running the script on one of the latest courses the below error message shows.

Traceback (most recent call last):
  File "linkedin_learning.py", line 226, in <module>
    loop.run_until_complete(process())
  File "C:\Program Files\Python36\lib\asyncio\base_events.py", line 466, in run_until_complete
    return future.result()
  File "linkedin_learning.py", line 214, in process
    await fetch_courses()
  File "linkedin_learning.py", line 102, in fetch_courses
    return await asyncio.gather(*map(fetch_course, COURSES))
  File "linkedin_learning.py", line 119, in fetch_course
    await fetch_chapters(course)
  File "linkedin_learning.py", line 131, in fetch_chapters
    await asyncio.gather(*chain.from_iterable(fetch_chapter(course, chapter) for chapter in course.chapters))
  File "linkedin_learning.py", line 166, in fetch_video
    subtitles = data['elements'][0]['selectedVideo']['transcript']['lines']
KeyError: 'transcript'

Problem is that the course has no transcripts, yet.

Implementation of detection and skipping of transcripts if none detected would be great.

**Comment by MagicRico** [comment]
> 
> 
> While running the script on one of the latest courses the below error message shows.
> 
> Traceback (most recent call last):
> File "linkedin_learning.py", line 226, in
> loop.run_until_complete(process())
> File "C:\Program Files\Python36\lib\asyncio\base_events.py", line 466, in run_until_complete
> return future.result()
> File "linkedin_learning.py", line 214, in process
> await fetch_courses()
> File "linkedin_learning.py", line 102, in fetch_courses
> return await asyncio.gather(*map(fetch_course, COURSES))
> File "linkedin_learning.py", line 119, in fetch_course
> await fetch_chapters(course)
> File "linkedin_learning.py", line 131, in fetch_chapters
> await asyncio.gather(*chain.from_iterable(fetch_chapter(course, chapter) for chapter in course.chapters))
> File "linkedin_learning.py", line 166, in fetch_video
> subtitles = data['elements'][0]['selectedVideo']['transcript']['lines']
> KeyError: 'transcript'
> 
> Problem is that the course has no transcripts, yet.
> 
> Implementation of detection and skipping of transcripts if none detected would be great.

It seems you have problem to download the transcript. In some courses, it bugs to download the transcript. So if you don't especially need it, better to disable the function to download it.

**Comment by liranbg** [comment]
fixed on #21 && #22
