### ISSUE TITLE
Csfr

### ISSUE THREAD

**Issue by armia142** [liranbg/linkedin-learning-downloader#8]
![000157-select c__python27_python exe](https://user-images.githubusercontent.com/40745071/46572425-c18ee180-c985-11e8-831b-7066c10aff5a.jpg)

I don't know what happens but I got that screen then it suddenly the python shutdown and nothing happen !! anyone knows how to proceed with the downloading ?!

**Comment by MagicRico** [comment]
> 
> 
> ![000157-select c__python27_python exe](https://user-images.githubusercontent.com/40745071/46572425-c18ee180-c985-11e8-831b-7066c10aff5a.jpg)
> 
> I don't know what happens but I got that screen then it suddenly the python shutdown and nothing happen !! anyone knows how to proceed with the downloading ?!

If you are trying to use the script, probably you should use python 3.6 or above

**Comment by liranbg** [comment]
fixed on #21 && #22
